name: Build and Release
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  PROJECT_NAME: quackmire

jobs:
  build-and-release:
    strategy:
      matrix:
        include:
          - name: linux
            runner: ubuntu-20.04
          - name: windows
            runner: windows-latest
          - name: macos
            runner: macos-latest

    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tauri Dependencies
        if: matrix.runner == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "Release ${{ github.ref_name }}"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
